version: "3.8"

volumes:
  hoge:
  zixin_db:


services:
  frontend:
    container_name: LBT-GPT
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/frontend
      - hoge:/frontend/node_modules
    working_dir: /frontend
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: bash -c "yarn build"
    # command: bash -c "yarn start"
  backend:
    container_name: vis_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4003:3003
    volumes:
      - ./backend:/backend
    tty: true
    depends_on:
      - db
    stdin_open: true
    platform: linux/x86_64
    command: >
      bash -c "rails db:migrate &&
        rm -f tmp/pids/server.pid &&
        rails s -p 3003 -b '0.0.0.0'"
  db:
    container_name: vis_db
    build: ./db
    volumes:
      - zixin_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: x3Ad6kCi
      PGPORT: 5434
    ports:
      - 5434:5434
    tty: true
    stdin_open: true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./build:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
